console.log('index.js被加载了~')
document.getElementById('btn').onclick=function(){
  //懒加载：当文件需要使用时加载
  //还有一种叫预加载:在js文件使用之前，预先加载jswen文件
  //正常加载可以认为并行加载（同一时间加载多个文件）;预加载prefetch:等其他资源加载完毕，其他资源空闲了，再偷偷加载
  import(/*webpackChunkName:'test',webpackPrefetch:true*/'./test').then(
  ({mul})=>{
   console.log(mul(4,5)) 
  }
  ).catch()
}