/**
 * 开发环境配置，能让代码运行即可
 * ***/
const {resolve}=require('path')
const htmlWebpackPlugin=require('html-webpack-plugin')
module.exports={
    entry:'./src/js/index.js',
    output:{
        filename:'js/built.js',//打包后的js放在js文件夹下
        path:resolve(__dirname,'build')
    },
    module:{
        rules:[
            //loader
            {
                test:/\.less$/,
                use:[
                    'style-loader',
                    'css-loader',
                    'less-loader'
                ]
            },
            //处理css资源
            {
                test:/\.css$/,
                use:[
                    'style-loader',
                    'css-loader'
                ]
            },
            //图片资源
            {
                test:/\.(jpg|png|gif)$/,
                loader:'url-loader',
                options:{
                    limit:8*1024,
                    name:'[hash:10].[ext]',
                 //关闭es6模块化
                esModule:false,
                outputPath:'imgs'//打包后的图片放在imgs文件夹下
                },      
            },
            //处理html中的图片资源img
            {
             test:/\.html$/,
             loader:'html-loader'
            },
            //处理其他资源
            {
              exclude:/\.(html|js|css|less|jpg|png|gif)$/,
              loader:'file-loader',
              options:{
                name:'[hash:10].[ext]',
                outputPath:'media'
              }
            }   
        ], 
    },
    plugins:[
        new htmlWebpackPlugin({
            template:'./src/index.html'
        })
    ],
    mode:'development',
    devServer:{
        contentBase:resolve(__dirname,'build'),
        compress:true,
        port:3000,
        open:true
    }
}